Feature/mrti 3027
cert-orangecyberdefense/datalake pull request #13
Opened 2020-11-10 13:05 UTC by Hugo-C

add_threats now use the API bulk endpoints if possible

2020-11-12 08:35 UTC, jakubbanas requested changes

2020-11-12 08:35 UTC, jakubbanas commented on datalake_scripts/engines/post_engine.py
> +        else:
Maybe it would be nice to return the errors list in that case, so the user would know which file rows are not correct.

2020-11-12 08:35 UTC, jakubbanas commented on datalake_scripts/engines/post_engine.py
> +        else:
Also, when some values in a batch would be not correct it would be difficult to say which atom was created, and which not.

Let's say we have 300 IPs, and one of those is invalid - in that case, only 200 will be created, because one batch will be discarded because of this one incorrect IP. In the output, the user will only see hashes, so there is no way to check which values were rejected.

2020-11-12 14:54 UTC, Hugo-C commented on datalake_scripts/engines/post_engine.py
> +        else:
I don't know what we should do then ?  
If the API reject whole batches we should log failed them I suppose but that's a bit wordy :smile:. Since we keep the insertion order from the file, maybe we should only log a range ? like:
> threats from \<value1\> to \<value2\> failed to be created  

Is that ok for you ?

2020-11-13 15:32 UTC, jakubbanas commented on datalake_scripts/engines/post_engine.py
> +        else:
I guess logging failed batches would be enough, good idea!

2020-11-13 15:33 UTC, jakubbanas approved these changes

2020-11-26 12:37 UTC, joginsky commented on datalake_scripts/engines/post_engine.py
> +            payload['atom_values'] = batch
This changed in current develop. `atom_values` is not a list anymore. It's a raw content of a .csv file.

2020-12-02 12:42 UTC, jziolkowski approved these changes

2020-12-03 17:06 UTC, merged