feature/mrti 3390 # Add bulk lookup in CLI
cert-orangecyberdefense/datalake pull request #18
Opened 2021-03-30 07:42 UTC by juan-kabbali

The command was added as `bulk_lookup_threats `

```
ocd-dtl bulk_lookup_threats < VAL ... > [--ip VAL ... | --file VAL ... | --domain VAL ...] -i [atomtype:path/to/file.txt ...]
```

For more information about how to use it go [here](https://github.com/cert-orangecyberdefense/datalake/blob/9ee7d59275098883ef2532cd378da0a57b4c4401/docs/Bulk_lookup_threats.md)

2021-05-12 05:07 UTC, joginsky approved these changes

2021-05-17 15:21 UTC, Hugo-C requested changes

2021-05-17 15:21 UTC, Hugo-C commented on docs/Bulk_lookup_threats.md
> +```
:+1:

2021-05-17 15:21 UTC, Hugo-C commented on docs/Bulk_lookup_threats.md
> +    -cc CC
typo: missing "-"

2021-05-17 15:21 UTC, Hugo-C commented on datalake_scripts/scripts/bulk_lookup_threats.py
> +    )
Default is json.
Also please add it to Bulk_lookup_threats.md

2021-05-18 15:41 UTC, Hugo-C requested changes
Please look at:
* https://github.com/cert-orangecyberdefense/datalake/pull/18#discussion_r633621488
* https://github.com/cert-orangecyberdefense/datalake/pull/18#discussion_r633557072
* (Optionally) https://github.com/cert-orangecyberdefense/datalake/pull/18#discussion_r633606173

2021-05-18 15:41 UTC, Hugo-C commented on datalake_scripts/scripts/bulk_lookup_threats.py
> +            found = atom.get('threat_found', True) if 'threat_found' in atom.keys() else True
`atom.get('threat_found', True)` should be enough no ? no need for the if/else

2021-05-19 14:37 UTC, Hugo-C approved these changes

2021-05-19 14:39 UTC, Hugo-C commented
Remember to bump setup.py before merging :)

2021-05-20 14:03 UTC, merged