MRTI-3616 # split big input files and quiet output by default
cert-orangecyberdefense/datalake pull request #27
Opened 2021-06-08 07:38 UTC by samah17

2021-06-08 17:34 UTC, juan-kabbali approved these changes

2021-06-08 17:34 UTC, juan-kabbali commented on datalake_scripts/scripts/bulk_lookup_threats.py
> +        starter.save_output(args.output, response,request_index)
missing white space after 'comma'  `starter.save_output(args.output, response,request_index)`

2021-06-08 17:34 UTC, juan-kabbali commented on datalake_scripts/scripts/bulk_lookup_threats.py
> +            size_limit = 500
This could be defined outside the `for` to avoid re-declaring it at each loop

2021-06-11 12:04 UTC, Hugo-C requested changes

2021-06-11 12:04 UTC, Hugo-C commented on datalake_scripts/common/base_script.py
> +    def _split_input_file(self, input_file, n):
no need for the `_` prefix if it is used by external code

2021-06-11 12:11 UTC, Hugo-C commented on datalake_scripts/scripts/bulk_lookup_threats.py
> +        size_limit = 500
With the command:
```
bulk_lookup_threats.py -i ip:input.text reverso.net --domain paiza.com --ip 45.96.65.132 -o output.json -ad -e preprod
```
(I took the IP from https://raw.githubusercontent.com/nl8590687/spam-list/master/spam-ip-list.txt)
I got :
```
API returned non 2xx response code : 429
{"message":"Number of threats to lookup is over request limit (max 500)"}
```
I don't know what the issue is :/

2021-07-05 07:42 UTC, Hugo-C approved these changes

2021-07-05 07:42 UTC, Hugo-C commented on datalake_scripts/common/base_script.py
> +        with open(file_name, 'a+') as file_to_write:
Please rollback if no longer needed

2021-07-05 08:35 UTC, merged