Feature/mrti 3648
cert-orangecyberdefense/datalake pull request #28
Opened 2021-06-22 14:56 UTC by samah17

2021-06-25 15:20 UTC, Hugo-C requested changes

2021-06-25 15:20 UTC, Hugo-C commented on datalake_scripts/datalake.py
> +        :param atom_type: must be one of the authorized_atom_value
It would be nice to precise that if the atom_type is not given, it'll be defined at the cost of an API call

2021-06-25 15:20 UTC, Hugo-C commented on datalake_scripts/datalake.py
> +                exit(1)
We can't have `exit` in the library. You'll need to raise an exception (generic or custom).

2021-06-25 15:20 UTC, Hugo-C commented on datalake_scripts/datalake.py
> +                exit(1)
Logs should also only be used to debug, not to communicate errors to users.

2021-06-25 15:20 UTC, Hugo-C commented on datalake_scripts/common/token_manager.py
> +            password = os.getenv('OCD_DTL_PASSWORD') or getpass()
If we want to be extra flexible, we should accept also username/password independently.
So we can have something like:
```python
username = username or os.getenv('OCD_DTL_USERNAME') or input('Email: ')
password = password or os.getenv('OCD_DTL_PASSWORD') or getpass()
```

2021-06-25 15:20 UTC, Hugo-C commented on tutorial.md
> +## About the parametrs
typo

2021-06-25 15:20 UTC, Hugo-C commented on tutorial.md
> +    datalake = Datalake()
This is mostly redundant, we can keep `datalake = Datalake()` and add it to the above code example

2021-06-25 15:20 UTC, Hugo-C commented on tutorial.md
> +then declare an istance of that class with your credentials
typo on instance

2021-06-25 15:20 UTC, Hugo-C commented on tutorial.md
> +                        password = os.getenv('OCD_DTL_PASSWORD'))
If the os env are set the dev can directly do `datalake = Datalake()` :/

2021-06-25 15:20 UTC, Hugo-C commented on tutorial.md
> +    datalake.look_up_threat(threat, atom_type, hashkey_only)
I think having the parameters define at the same place would be more clear, like:
```python
datalake.look_up_threat(
  threat='mayoclinic.org', 
  atom_type='domain', 
  hashkey_only=False,
)

2021-06-25 15:23 UTC, Hugo-C commented on tutorial.md
> +     ____        _        _       _
I think we should put a link from the README.md to this file, maybe before or next to `### Using a script` => `### Using as a library`

2021-06-27 16:47 UTC, juan-kabbali requested changes

2021-06-28 14:57 UTC, Hugo-C commented on datalake_scripts/datalake.py
> +class Datalake:
No need to use os env :/ 
What about:
```python
Datalake(username='some username', password='some password')
```

2021-06-28 14:57 UTC, Hugo-C commented on README.md
> +### Using a script ==> [Using as a library](datalake/tutorial.md)
It could be better I think, maybe something like ?
### Using as a Library
see [the following link](tutorial.md)
### Using as a CLI 
...

2021-06-28 14:57 UTC, Hugo-C commented on datalake_scripts/datalake.py
> +                          if this atom_type is not given,
doc cut short ?

2021-06-28 14:57 UTC, Hugo-C commented on tutorial.md
> +     ____        _        _       _
@samah17 my bad it wasn't an example but just a proposition for the sections order :sweat_smile:

2021-06-28 14:58 UTC, Hugo-C approved these changes

2021-06-28 15:21 UTC, samah17 commented on datalake_scripts/datalake.py
> +                          if this atom_type is not given,
yes my bad will rectify that

2021-06-28 16:02 UTC, juan-kabbali approved these changes
Functionally the PR is nice 😎 but it could be enhanced in terms of syntax and code format.

2022-02-07 14:21 UTC, Hugo-C commented
PR was a POC. The essential content was merged under other PRs

2022-02-07 14:21 UTC, closed without merging