MRTI-4090 # bulk edit score
cert-orangecyberdefense/datalake pull request #34
Opened 2021-12-07 09:56 UTC by mrtnhw

Added bulk edit score in library,
CLI now uses the newly implemented bulk edit score.
Batches hashkeys by 100 and queries the API.

2021-12-30 15:11 UTC, Hugo-C requested changes

2021-12-30 15:11 UTC, Hugo-C commented on tutorial.md
> +* `whitelist`: A boolean, if no `threat_types` are provided, this argument should be set to true. All score values will then be set to 0. If `threat_types` are provided along with `whitelist` set as
nice doc, I only see this False not formatted :p

2021-12-30 15:11 UTC, Hugo-C commented on tutorial.md
> +    {'threat_type': ThreatType('ddos'), 'score': 5},
it should be `ThreatType.DDOS` instead :/

2021-12-30 15:11 UTC, Hugo-C commented on tutorial.md
> +dtl.Threats.edit_score_by_query_body_hash(query_body_hash, threat_Scores_list, permanent)
permanent should not be a bool but a `OverrideType` (keeping doc updated is a pain :'( )

2022-01-03 15:02 UTC, mrtnhw commented on datalake/endpoints/threats.py
> +                                      override_type: OverrideType = OverrideType.TEMPORARY):
Same, but PEP8 wants it that way :(
Should I ignore PEP8 and change it to what you suggested ?

2022-01-03 15:11 UTC, mrtnhw commented on datalake/endpoints/threats.py
> +    def __build_scores(scores_list: List[Dict[str, int]]):
My understanding was that 2 underscores meant that the function was private. 
However here is what the PEP8 doc says :
"If your class is intended to be subclassed, and you have attributes that you do not want subclasses to use, consider naming them with double leading underscores and no trailing underscores. This invokes Python's name mangling algorithm, where the name of the class is mangled into the attribute name. This helps avoid attribute name collisions should subclasses inadvertently contain attributes with the same name."
I will thus remove the double underscore.

2022-01-04 08:34 UTC, mrtnhw commented on datalake/endpoints/threats.py
> +                ...  # logger.warning(f'batch of threats from {batch[0]} to {batch[-1]} failed to be created')
My bad, fixed. Failed batch creation's atom values will be recorded in the same format as failed bulk add, in failed>failed_atom_values

2022-01-04 08:38 UTC, mrtnhw commented on datalake/endpoints/threats.py
> +                f_atom_val.append(atom_value)
Removed redundant variable and for loop.

2022-01-04 10:20 UTC, mrtnhw commented on datalake/endpoints/threats.py
> +            payload['threat_data']['content'][key_value] = {'number': int(value)}
I checked the API and find the following in `tdcapi-portal-api/tdcapi_portal/mrti/models/manual_threat.py`
`
elif self.atom_type == 'cc':
    cc_utils.CardValidator().check(str(atom_value))
`
Seems like it's expecting a string ? Couldn't find anything better :/

2022-01-04 14:37 UTC, mrtnhw commented on datalake_scripts/scripts/add_threats.py
> +    threat_types = parse_threat_types(args.threat_types) or []
I left it as it was but after checking it's useless so I'm removing it :)

2022-01-04 17:01 UTC, Hugo-C commented on datalake_scripts/scripts/edit_score.py
> +            logger.warning('\x1b[6;30;41mBATCH ' + str(index+1) + ': FAILED\x1b[0m')
@mrtnhw should we talk about this point ?
We can also drop it if you prefer

2022-01-04 17:03 UTC, Hugo-C approved these changes

2022-01-04 17:20 UTC, Hugo-C commented on datalake/endpoints/threats.py
> +                                      override_type: OverrideType = OverrideType.TEMPORARY):
PEP8 is not very strict I think, but
```python3
result = some_function_that_takes_arguments(
    'a', 'b', 'c',
    'd', 'e', 'f',
)
```
is [accepted](https://pep8.org/#indentation) so I think we are compliant :p

2022-01-05 09:12 UTC, mrtnhw commented on datalake_scripts/scripts/edit_score.py
> +            logger.warning('\x1b[6;30;41mBATCH ' + str(index+1) + ': FAILED\x1b[0m')
Sure, I switched to f-strings and added a count of the batches on script completion. 
If you want to show the number of batches while the script is in progress then I think I will need to make big changes.

2022-01-05 10:24 UTC, Hugo-C approved these changes

2022-01-05 11:32 UTC, Hugo-C commented
I see that for add_threats output file is a list of json files, it is not ideal but let's keep it like that for now

2022-01-05 11:35 UTC, Hugo-C commented
It's outside of this PR scope, but please add the option to pass multiple `-t` to edit_score, like for add_threats

2022-01-05 16:43 UTC, Hugo-C requested changes

2022-01-05 16:43 UTC, Hugo-C commented on datalake/endpoints/threats.py
> +    def add_threat(
Few remarks about the lib interface.
`add_threat` accept any length of atoms unlike `edit_score_by_hashkeys` which is fine by me, but it should be very explicit (the best would be a line in each functions documentation + a check for the list to not exceed 100 in `edit_score_by_hashkeys` (maybe the max should be an env var to follow the API changes ?)).
Also let's rename `add_threat` to `add_threats` if it can add multiple one at once ^^

2022-01-12 15:23 UTC, Hugo-C approved these changes

2022-01-12 15:41 UTC, merged