MRTI-4432#
cert-orangecyberdefense/datalake pull request #46
Opened 2022-05-11 15:05 UTC by mrtnhwtt

added dataclass constructors for atom in the library
Added sighting submit and get method for the library

2022-05-12 07:24 UTC, Hugo-C commented
> Need to remove tests for 3.6 as we implemented dataclasses

We should bump 3.6 tests to 3.7 and 3.9 to 3.10 I guess

2022-05-17 10:12 UTC, Hugo-C requested changes
Where are the tests ?
* generate_atom_json should be easy to test for a couple of AtomType
* submit_sighting also have to be tested, in particular that the payload sent to the API is as expected

2022-05-17 10:12 UTC, Hugo-C commented on datalake/common/atom_type.py
> +            warnings.warn("Some keys aren't allowed for sightings and thus will be removed if you have set them. Check the classes for information on which keys are allowed. To stop this warning from
\+ we should output a warning only when a key is ignored :'( 
So I guess `_sightings_factory` have to be refactored.

2022-05-17 13:52 UTC, mrtnhwtt commented on datalake/endpoints/sightings.py
> +                                 'an instance of the Visibility class')
Added a ValueError. A bit weird to raise an Error saying a value isn't needed but it can help the user better understand what a neutral sighting is.

2022-05-17 13:57 UTC, mrtnhwtt commented on datalake/endpoints/sightings.py
> +                    payload = {key: payload.get(key, []) + atom_dict.get(key, []) for key in set(list(payload.keys()) + list(atom_dict.keys()))}
I like the first one, it makes it a bit more readable.

2022-05-17 14:14 UTC, mrtnhwtt commented on tutorial.md
> +end = (datetime.fromtimestamp(1620742823)).strftime("%Y-%m-%dT%H:%M:%SZ")
I want to leave the date format in the documentation so that users can easily find it. 
I went with 
`start = (datetime.datetime.utcnow()).strftime("%Y-%m-%dT%H:%M:%SZ")
end = (datetime.datetime.utcnow() - datetime.timedelta(hours=1)).strftime("%Y-%m-%dT%H:%M:%SZ")
`

2022-05-17 14:17 UTC, mrtnhwtt commented on datalake/config/endpoints.json
> +    "preprod": "https://ti-dev.extranet.mrti-center.com/api/",
oops

2022-05-17 14:18 UTC, mrtnhwtt commented on datalake/common/atom_type.py
> +            warnings.warn("Some keys aren't allowed for sightings and thus will be removed if you have set them. Check the classes for information on which keys are allowed. To stop this warning from
While refactoring `_sightings_factory` I noticed a problem with my previous implementation for nested classes. I refactored the `_sightings_factory` and changed the way the final dict is generated.

2022-05-20 10:40 UTC, Hugo-C requested changes

2022-05-20 10:40 UTC, Hugo-C commented on tests/lib/test_atom_type.py
> +    assert expected_output == output
Testing that the warning was triggered could be a nice idea.
As I didn't want to commit directly, here is a proposition (in Pycharm it can be used via Git > Patch > Apply Patch from Clipboard):
```diff
Index: tests/lib/test_atom_type.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tests/lib/test_atom_type.py b/tests/lib/test_atom_type.py
--- a/tests/lib/test_atom_type.py	(revision f69f2a56c954a7731dad0c8eaf9b69840b6577c4)
+++ b/tests/lib/test_atom_type.py	(date 1653042614366)
@@ -1,4 +1,6 @@
-import pytest
+from unittest.mock import patch
+import warnings  # noqa needed mocking
+
 
 from tests.common.fixture import datalake  # noqa needed fixture import
 from datalake import IpAtom, FileAtom, Hashes, Jarm, IpService
@@ -74,7 +76,8 @@
     assert expect_output == output
 
 
-def test_generate_atom_json_nested_remove_unused_keys_for_sightings(datalake):
+@patch('warnings.warn')
+def test_generate_atom_json_nested_remove_unused_keys_for_sightings(warn_mock, datalake):
     expected_output = {
         'file_list': [
             {
@@ -90,6 +93,7 @@
     output = file_atom.generate_atom_json(for_sightings=True)
 
     assert expected_output == output
+    assert warn_mock.called
 
 def test_generate_atom_json_nested(datalake):
     expected_output = {
Index: datalake/common/warn.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/datalake/common/warn.py b/datalake/common/warn.py
--- a/datalake/common/warn.py	(revision f69f2a56c954a7731dad0c8eaf9b69840b6577c4)
+++ b/datalake/common/warn.py	(date 1653042695970)
@@ -5,5 +5,5 @@
 class Warn:
     @staticmethod
     def warning(message):
-        if bool(os.environ.get('IGNORE_SIGHTING_BUILDER_WARNING')):
+        if not bool(os.environ.get('IGNORE_SIGHTING_BUILDER_WARNING')):
             warnings.warn(message)
```

2022-05-23 09:37 UTC, mrtnhwtt commented on tests/lib/test_sightings.py
> +    'ipv4',
Oops, fixed. Thx.

2022-05-23 13:44 UTC, mrtnhwtt commented on tests/lib/test_atom_type.py
> +    assert expected_output == output
Took me some time because it seemed to me like it wasn't working. Turns out when I was testing with the env IGNORE_SIGHTING_BUILDER_WARNING set to false, literally the `false` string, bool evaluates it to `True` because the string is set.
Is this the behaviour we want ?
I changed the conditional for warning to the following:
```
if not os.environ.get('IGNORE_SIGHTING_BUILDER_WARNING', 'False').lower() in ('true', '1', 't'):
```
Now it will display the message if the env variable is set to false or if it's not set :)

2022-05-24 11:19 UTC, Hugo-C commented on datalake/config/endpoints.json
> +    "preprod": "https://ti-dev.extranet.mrti-center.com/api/",
@mrtnhwtt  still not fixed isn't it ? :'(

2022-05-24 11:31 UTC, Hugo-C commented on tests/lib/test_atom_type.py
> +    assert expected_output == output
Good catch on bool/string :)
Separate tests are always better :ok_hand:

2022-05-24 11:35 UTC, Hugo-C approved these changes
Please fix https://github.com/cert-orangecyberdefense/datalake/pull/46#discussion_r873819035
Then feel free to merge :)

2022-05-24 13:15 UTC, mrtnhwtt commented on datalake/config/endpoints.json
> +    "preprod": "https://ti-dev.extranet.mrti-center.com/api/",
Fixed it and then revert it back for tests and forgot about it again ^^
My bad ! fixed now. for good.

2022-05-24 13:20 UTC, merged