Update threats-manual for new dataclass builders
cert-orangecyberdefense/datalake pull request #49
Opened 2022-05-24 14:17 UTC by mrtnhwtt

Updated `Threats.add_threats` to allow users to add more data to the threats they submit
Updated the CLI to use the new version of `add_threats`
Fixed typo in IpAtom.

2022-05-25 07:29 UTC, Hugo-C requested changes

2022-05-25 07:29 UTC, Hugo-C commented on datalake/endpoints/threats.py
> +            raise TypeError("atoms needs to be a list of Atom subclasses.")
Checking the atom is a subclass but not the abstract class is a bit too extreme in my opinion ^^ 
The error message is now obsolete, atom is not a list

2022-05-25 07:29 UTC, Hugo-C commented on datalake_scripts/scripts/add_threats.py
> +        atom = SslAtom(external_analysis_link=link, **{hash_to_name(value): value})
:warning: `Hashes` constructor is not called

2022-05-25 07:29 UTC, Hugo-C commented on datalake_scripts/scripts/add_threats.py
> +    if atom_type.value == 'apk':
Why not compare the Enum directly ? :/ 
like: `atom_type == AtomType.APK`

2022-05-25 07:29 UTC, Hugo-C commented on datalake_scripts/scripts/add_threats.py
> +    return hash_name_str
```python
return hash_list.get(len(hash_), 'ssdeep')
```
seems better, extremist would even put the dict literal instead of hash_list, but we are not of this kind ;)

2022-05-25 07:29 UTC, Hugo-C commented on datalake_scripts/scripts/add_threats.py
> +        atom = ApkAtom(external_analysis_link=link, android=AndroidApp(package_name), hashes=Hashes(**{hash_to_name(apk_hash): apk_hash}))
I would assign `Hashes(...` to a variable to reduce the line length

2022-05-25 09:44 UTC, mrtnhwtt commented on datalake/endpoints/threats.py
> +            raise TypeError("atoms needs to be a list of Atom subclasses.")
Should I only check if it's not an instance of atom then?

2022-05-25 09:57 UTC, mrtnhwtt commented on datalake_scripts/scripts/add_threats.py
> +        atom = ApkAtom(external_analysis_link=link, android=AndroidApp(package_name), hashes=Hashes(**{hash_to_name(apk_hash): apk_hash}))
Functional programming made me want to avoid side effect at all costs 👀

2022-06-01 10:19 UTC, Hugo-C commented on datalake/endpoints/threats.py
> +            raise TypeError("atoms needs to be a list of Atom subclasses.")
It's correct so let's keep it ^^

2022-06-01 11:37 UTC, Hugo-C approved these changes

2022-06-01 13:13 UTC, merged