MRTI-5423 # add post atom-values
cert-orangecyberdefense/datalake pull request #94
Opened 2023-10-10 09:17 UTC by ClaireOrange

2023-10-13 14:32 UTC, hugolivier requested changes

2023-10-13 14:32 UTC, hugolivier commented on datalake_scripts/engines/post_engine.py
> +        return parse_response(self.datalake_requests(self.url, "post", self._post_headers(output=type), payload))
parse_response should be removed here, as it fails with AttributeError: 'dict' object has no attribute 'headers'.
This is because self.datalake_requests already does the parsing, and return a dict or a str.

2023-10-13 14:32 UTC, hugolivier commented on requirements.txt
> +click===8.0.0
click is not used

2023-10-13 16:23 UTC, ClaireOrange commented on requirements.txt
> +click===8.0.0
I wanted it for tests but it will be done on another ticket

2023-10-17 09:43 UTC, cert-orangecyberdefense commented
The code is clear, good use of types, good readme, well done @ClaireOrange.

I have one question still :

The user is forced to use normalized timestamp, it may not be the easiest way to handle date, you could create a function that handle timestamp conversion from UTC classic datetime : (2023-10-17)

You can use Python's datetime library to convert a classic UTC datetime string to  ISO 8601 formatted UTC timestamp string. Below is an example function that takes a UTC datetime string in the format YYYY-MM-DD and returns a normalized timestamp.

```
from datetime import datetime, timezone

def convert_to_iso8601_timestamp(utc_datetime_str):
    try:
        dt_object = datetime.strptime(utc_datetime_str, '%Y-%m-%d')
        dt_object = dt_object.replace(tzinfo=timezone.utc)
        iso8601_timestamp = dt_object.isoformat(timespec='milliseconds') + 'Z'
        return iso8601_timestamp
    except Exception as e:
        print(f"An error occurred: {e}")
        return None
```

2023-10-19 09:09 UTC, hugolivier approved these changes

2023-10-19 13:53 UTC, merged