MRTI-5647: #Add filtered tag and subcategory list
cert-orangecyberdefense/datalake pull request #96
Opened 2023-11-07 15:45 UTC by samy2rafraf

2023-11-13 16:17 UTC, ClaireOrange requested changes
The PR must be on branch `develop` as mentionned in the documentation on Confluence

2023-11-14 15:00 UTC, ClaireOrange requested changes

2023-11-14 15:00 UTC, ClaireOrange commented on docs/Get_Filtered_Tags_Subcategory.md
> +
the option --output is missing, as is the option --env

2023-11-14 15:00 UTC, ClaireOrange commented on datalake/endpoints/filtered_tag_subcategory.py
> +            if "No tag category found:" in str(ve):
I think we should not ignore the ValueError  `No tag category found:`
To me, it occurs when I provide a bad category_name (ie that does not exists) -> so the user whould be warned in that case that its query is invalid 
Example : 
```
params = {
        "category_name": "VulnerabilityBad",
        "limit": 5,
        "offset": 0,
    }
response2 = dtl.FilteredTagSubcategory.get_filtered_and_sorted_list(**params)
```

But maybe the message "No tag category found:" is not very clear, maybe you can rename the ValueError message by `raise ValueError("Invalid category_name input")` or `raise ValueError(Incorrect category_name provided")`



FYI, When a query is valid (ie with a good catgeory name) but that we got no match, we get no error but an empty result as expected : 
```
params = {
        "category_name": "Malware",
        "ids": [1,"strange"],
        "limit": 2,
        "offset": 1,
        "ordering": "created_at"
    }
response6 = dtl.FilteredTagSubcategory.get_filtered_and_sorted_list(**params)
print(response6)
------------------------------------------------------------
{'count': 0, 'results': []}
```
That's why I suspect the ValueError send by the API is more than just no match :)

2023-11-14 15:00 UTC, ClaireOrange commented on datalake_scripts/scripts/get_filtered_tag_subcategory.py
> +from datalake.endpoints.filtered_tag_subcategory import FilteredTagSubcategory
I'm afraid that quite not as simple as that : you cannot use the function you created in datalake/endpoints
You will have to create a similar class/function in the datalake_scripts.engines.post_engine

For now, your command appears as  available in the CLI command (because you updated cli.py) : 
```
`ocd-dtl -h
usage: 
            ocd-dtl <command> [<args>]

The most commonly used ocd-dtl commands are:
   add_threats     Submit a new threat to Datalake from a file
   get_threats     Retrieve threats (as Json) from a list of ids (hashkeys)
   edit_score      Edit scores of a specified list of ids (hashkeys)
            

Cli to interact with OCD's Datalake

positional arguments:
  {add_comment,add_tags,add_threats,advanced_search,bulk_lookup_threats,edit_score,get_atom_values,get_filtered_tag_subcategory,get_query_hash,get_threats,get_threats_from_query_hash,lookup_threats}
                        Subcommand to run

optional arguments:
  -h, --help            show this help message and exit
  --version, -V         prints the current version

Don't hesitate to leave a feedback on https://datalake.cert.orangecyberdefense.com/gui/ using the "Add Feedback"
button`
```

But it cannot be actually called : 
```
`ocd-dtl get_filtered_tag_subcategory

usage: ocd-dtl [-h] [-o OUTPUT] [-e {prod,preprod}] [--debug] [-q]
ocd-dtl: error: unrecognized arguments: get_filtered_tag_subcategory`
```

2023-11-14 15:00 UTC, ClaireOrange commented on datalake_scripts/scripts/get_filtered_tag_subcategory.py
> +    )
in case ordering, or name or ids or other commented arguments are given with the command, are you sure they will be taken into account ?

2023-11-20 10:08 UTC, samy2rafraf commented on docs/Get_Filtered_Tags_Subcategory.md
> +
Option --output and option --env are global arguments, not specific args linked to this function/script

2023-11-20 10:08 UTC, samy2rafraf commented on docs/Get_Filtered_Tags_Subcategory.md
> +
all args are optional

2023-11-20 10:09 UTC, samy2rafraf commented on docs/Get_Filtered_Tags_Subcategory.md
> +
mooved

2023-11-20 10:09 UTC, samy2rafraf commented on docs/Get_Filtered_Tags_Subcategory.md
> +```commandline
removed, and added some default values to doc

2023-11-21 13:15 UTC, samy2rafraf commented on datalake/endpoints/filtered_tag_subcategory.py
> +            if "No tag category found:" in str(ve):
`
Traceback (most recent call last):
  File "zouzou.py", line 10, in <module>
    response2 = dtl.FilteredTagSubcategory.get_filtered_and_sorted_list(**params)
  File "/home/cybx8064/Repo/datalake/datalake/endpoints/filtered_tag_subcategory.py", line 37, in get_filtered_and_sorted_list
    response = self.datalake_requests(
  File "/home/cybx8064/Repo/datalake/datalake/common/throttler.py", line 34, in wrapped
    response = f(*args, **kwargs)
  File "/home/cybx8064/Repo/datalake/datalake/endpoints/endpoint.py", line 89, in datalake_requests
    raise ValueError(f"422 HTTP code: {error_msg}")
ValueError: 422 HTTP code: {'category_name': ['No tag category found: Vulnerabilityazez']}
`

This is API response to no matching tag.

2023-11-27 09:59 UTC, ClaireOrange requested changes

2023-11-27 09:59 UTC, ClaireOrange commented on datalake_scripts/cli.py
> +    def get_filtered_tag_subcategory(self, args):
why is this command not added with the _add_command_subparser like the other commands ?

2023-11-27 09:59 UTC, ClaireOrange commented on datalake_scripts/cli.py
> +        self._add_command_subparser(subparsers, "add_comments", add_comments.main)
We will need to think about adding this change in the breaking change info during the release
No action needed except to remind me of it when we will push the new release

2023-11-27 09:59 UTC, ClaireOrange commented on datalake/endpoints/filtered_tag_subcategory.py
> +        if ids:
I get errors when I try to use the ids parameters : 

params = {
    "category_name": "Malware",
    "ids": [1],
    "limit": 2,
    "offset": 1,
    "ordering": "created_at",
}
response6 = dtl.FilteredTagSubcategory.get_filtered_and_sorted_list(**params)

Traceback (most recent call last):
  File "t_script.py", line 58, in <module>
    response7 = dtl.FilteredTagSubcategory.get_filtered_and_sorted_list(**params)
  File "/home/jtmh7155/Documents/Git/datalake/datalake/endpoints/filtered_tag_subcategory.py", line 49, in get_filtered_and_sorted_list
    response = self.datalake_requests(
  File "/home/jtmh7155/Documents/Git/datalake/datalake/common/throttler.py", line 34, in wrapped
    response = f(*args, **kwargs)
  File "/home/jtmh7155/Documents/Git/datalake/datalake/endpoints/endpoint.py", line 89, in datalake_requests
    raise ValueError(f"422 HTTP code: {error_msg}")
ValueError: 422 HTTP code: {'ids': {'1': ['Not a valid integer.']}}

2023-11-27 10:32 UTC, samy2rafraf commented on datalake_scripts/cli.py
> +    def get_filtered_tag_subcategory(self, args):
Yeah, indeed i forgot to remove it, but it is already in the subparser commands.

2023-11-27 10:40 UTC, samy2rafraf commented on datalake/endpoints/filtered_tag_subcategory.py
> +        if ids:
It is working on my side 😢. @ClaireOrange 

from datalake import Datalake
params = {
"category_name": "Malware",
"ids": [10904, 10905],
"limit": 2,
"offset": 0,
"ordering": "created_at",
}
dtl = Datalake("<username>", "<password>")
print(dtl.FilteredTagSubcategory.get_filtered_and_sorted_list(**params))

Even with params.ids == [1]

2023-11-27 14:17 UTC, samy2rafraf commented on datalake/endpoints/filtered_tag_subcategory.py
> +        if ids:
Ok seen with Claire, it was a problem by her side.

2023-11-28 10:10 UTC, ulrichzang requested changes
Please for all my remarks concerning the CLI, make a check on the lib version of the feature if it need to be fixed.

2023-11-28 10:30 UTC, samy2rafraf commented on docs/Get_Filtered_Tags_Subcategory.md
> +ocd-dtl get_filtered_tag_subcategory --category_name malware --limit 10 --output malware_subcategories.json
Thx, done.

2023-11-28 14:48 UTC, ulrichzang commented on docs/Get_Filtered_Tags_Subcategory.md
> +ocd-dtl get_filtered_tag_subcategory --category_name malware --limit 10 --output malware_subcategories.json
```
:~/datalake(ci/feature/MRTI-5647)$ ocd-dtl get_filtered_tag_subcategory --category_name "attack pattern" --limit 10

Attack pattern is not a valid tag category name
:~/datalake(ci/feature/MRTI-5647)$ ocd-dtl get_filtered_tag_subcategory --category_name "Attack Pattern" --limit 
10

Attack pattern is not a valid tag category name
:~/datalake(ci/feature/MRTI-5647)$ ocd-dtl get_filtered_tag_subcategory --category_name "OCD - Threat pattern" --
limit 10

Ocd - threat pattern is not a valid tag category name
```

Ok for the a single word category_name but with two or plus (or complex one like `OCD - Threat pattern`)  it can be cubersome. So maybe for more than one word just keep it like that not doing any case transformation. Because like you see in the errors even if l enter a good category_name it is automatically transform.

The real deal is that there is no valid pattern define for the category_name in datalake. If this go wild maybe remove the feature for casting, and print to the user the valid available category_name on the API side. 
You can confirm with @ClaireOrange this approach.

2023-11-28 15:20 UTC, samy2rafraf commented on docs/Get_Filtered_Tags_Subcategory.md
> +ocd-dtl get_filtered_tag_subcategory --category_name malware --limit 10 --output malware_subcategories.json
Seen with Hugo, this format is not to be keep, so i removed the format thing.

Now if the user enter the wrong prompt, it will not try to format.

2023-11-28 15:35 UTC, ulrichzang approved these changes

2023-11-29 09:58 UTC, merged