Ci/feature/mrti 5554
cert-orangecyberdefense/datalake pull request #99
Opened 2023-11-16 17:48 UTC by ClaireOrange

2023-11-17 09:37 UTC, hugolivier approved these changes

2023-11-17 09:40 UTC, hugolivier commented
Suggestion : you can add in contributing.md that it is possible to run only specific tests by adding `path="path/to/file.py::test_name"` to tests commands.
For example :  `make test_dev_env path=tests/scripts/test_csv_builder.py::test_single_threat_no_details`

2023-11-20 09:30 UTC, samy2rafraf requested changes
looks good, typo in contributing.md

2023-11-20 09:30 UTC, samy2rafraf commented on CONTRIBUTING.md
> +In you create a new class, do not forget to add it to `./datalake/datalake.py`.
```suggestion
If you create a new class, do not forget to add it to `./datalake/datalake.py`.  
```

2023-11-20 09:52 UTC, samy2rafraf approved these changes

2023-11-22 09:48 UTC, merged